### PR TITLE
Solve the accessibility effect for CSS 'display' rules

### PR DESCRIPTION
**Pull request by jiayinjx**
"display:none / visibility:hidden / overflow:hidden " have the accessibility effect that content is ignored by screen readers

### CODE REVIEW

**Comment by timlevett** [comment]
@jhanstra - please check this out. Wouldn't this make it always show? even on non-hover state?

**Comment by jhanstra** [comment]
Yeah, that would make it always show. I don't think we want that. Take a look at this article, @jiayinjx: http://alistapart.com/article/now-you-see-me. There are some suggestions for what to do for elements that should be available to screen readers. The last option in the table is probably the best option for this situation - `position: absolute; left:-999em`.

**Comment by jiayinjx** [comment]
This is the same article I read. I tried to use position: absolute;
left:-999em., but after I switch "display : none" to it, the
'widget-remove' icon will disappear when hover.

**Comment by timlevett** [comment]
:+1:

**Comment by jhanstra** [comment]
:+1:

**Pull request merged**
