### PR TITLE
Actually true is false, and false is true

### PR DESCRIPTION
**Pull request by timlevett**
don't ask.

### CODE REVIEW

**Comment by apetro** [comment]
I don't understand this change, but if I did, maybe I'd come to understand that `$scope.loading = true;` does not mean "It is true that the page is still loading." and rather means something else ("It's true that the page is as loaded as it's ever gonna be.", say.)

If `$scope.loading = true` does not mean "the page is truly loading" and `$scope.loading = false` does not mean "the page is not loading", well, is there some renaming available that would make this loading indicator code easier to understand?

**Comment by timlevett** [comment]
Revamped `loading` to be `loaded`. Should make more sense now.

**Comment by Doug-Reed** [comment]
:+1:

**Comment by vertein** [comment]
👍

**Pull request merged**
