### PR TITLE
chore: adopt conventional commits standard

### PR DESCRIPTION
**Pull request by ChristianMurphy**
Hey @UW-Madison-DoIT/uportal-home-committers :wave: 

I've been thinking lately about how to manage releases, while looking at how [other open source projects](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit) have been approaching the problem, I came across [conventional commits](https://conventionalcommits.org/). :eyes: 

The goal  the conventional commits standard is to simplify management of semantic versioning. Metadata provided by commit messages is used to guide releases as MAJOR, MINOR, or PATCH. As well as give details needed to create CHANGELOGs in a rapid release cycle. :fast_forward: 

It seems like the standard could be a good fit with the existing processes and culture at Madison. :star: 
I'd be interested to hear your thoughts on whether adopting conventional commits could be a good idea. :thought_balloon: 

Technical changes in this PR:

* Add [commitlint](https://github.com/marionebl/commitlint/tree/master/%40commitlint/cli) to check commit messages
* Add git hook from [husky](https://github.com/typicode/husky) to trigger commitlint on every change
* Add [commitlint config angular](https://github.com/marionebl/commitlint/tree/master/@commitlint/config-angular), which checks conventional commits, and comes with preset types to use with conventional commits.

----

Contributor License Agreement adherence:

- [x] This Contribution is under the terms of Individual [Contributor License Agreements][] (and also Corporate Contributor License Agreements to the extent applicable) appearing in the [Apereo CLA roster][].

[Apereo CLA roster]: http://licensing.apereo.org/completed-clas
[Contributor License Agreements]: https://www.apereo.org/licensing/agreements

### CODE REVIEW

**Comment by jimhelwig** [comment]
I am not familiar with the details of this but the general philosophy as I understand it sounds good.

**Comment by davidmsibley** [comment]
We've been interested in things that would allow us to automate (or at least simplify) changelogs. This looks like it's worth some research. However, I hesitate to approve just because of the PR number :smiling_imp:

**Comment by apetro** [comment]
How does this relate to my habit of 
[squash-and-merge](https://github.com/blog/2141-squash-your-commits) such that the commits and commit messages of the feature branch don't end up in master, just a single squash commit? Hard to lint the squash commit commit message since it doesn't exist to be linted until it hits `master`.

**Comment by ChristianMurphy** [comment]
It would work okay.

I believe "Squash and Commit" allows for editing the message, so the messages could still follow the conventional commits format. :memo: 
You are right that those commits would not be automatically checked by the commit linter.
If the lack of linter for "squash and merge" is perceived as a high risk, the button can be disabled from the repository settings. :gear: 
I personally don't see that as a high risk. :white_check_mark:

**Comment by ChristianMurphy** [comment]
Also to be clear.
I don't think conventional commits is the *only* way to handle this.
Nor do I know if it is the best way.
It is just ***a*** way that several open source projects have used successfully.

Another could be adding a `CHANGELOG.md` file and requesting contributors add notes as they add fixes and features.
Keep a Changelog, advocates for this approach: http://keepachangelog.com/en/1.0.0/
Projects adopting that technique have also been successful.

**Comment by apetro** [comment]
So, the [label the pull requests solution](https://github.com/UW-Madison-DoIT/uw-frame/blob/master/docs/releasing.md#labeling-pull-requests), that's not sufficiently simplifying figuring out patch vs minor vs major in releasing. Because we're not doing it. That practice isn't documented in this repo, and it's not reminded of in the contributing guidance or the pull request template. So. Would that labeling meet the need if we doubled down on consistently doing it?

**Comment by vertein** [comment]
In practice, we haven't been labeling our PR's, and I'm fine with that.  It's been easy enough to manually go back and take a look and appropriately version the product.

My thought process is - I like the idea and like the thought of automating some change logs.  A little bit of thinking of the type of changes we make is healthy.

I also don't like automated change logs and prefer the human touch in release notes and I'm hesitant to add a check that a developer might have to look into and parse.

So far, I'm at the point where I'm either a +1 or a no-vote on this.  I would +1 the addition of a changelog with updated documentation stating our intentions.

**Comment by ChristianMurphy** [comment]
:thinking: @apetro It would help.
The challenge with pull requests, is they don't correlate to versions as cleanly as commits.
GitHub doesn't provide a UI to see which release a PR is in, you need to know to look for the merge commit, and check the included tags on that.

*However*, If both labels, and a milestone for the next release are used, that could work out nicely. :+1: 

The way I look at it there are two differentiating factors between: conventional commits, keep a changelog, and tag + milestone.
1. Is the Contributor or the Maintainer responsible for adding the data?
2. Is the data optional or required?

For Conventional Commits:
1. Contributor
2. Required

For Keep a Changelog:
1. Contributor
2. Optional

For Tag + Milestone:
1. Maintainer
2. Optional

I personally lean toward having Contributors add the information, and Maintainers review it.
I'm not the fence on if it should be optional or required (some small changes may.

**Comment by ChristianMurphy** [comment]
@vertein 

> I also don't like automated change logs and prefer the human touch in release notes and I'm hesitant to add a check that a developer might have to look into and parse.

I completely agree.
Mixing both is possible.
The Atom editor's change logs have a human written summary at the top, and the automated listing below.
https://github.com/atom/atom/releases/tag/v1.18.0

**Comment by ChristianMurphy** [comment]
> I also don't like automated change logs and prefer the human touch in release notes and I'm hesitant to add a check that a developer might have to look into and parse.
> So far, I'm at the point where I'm either a +1 or a no-vote on this. I would +1 the addition of a changelog with updated documentation stating our intentions.

@vertein I've opened #671 to add a human maintained `CHANGELOG`.

---

Even without it being used to create `CHANGELOG`s automatically.
I still see the metadata included in conventional commits as having merit on its own.

For example picking at one of my own commit messages. fc86bf69363dc18d1efbf2e603f554400ce1392a

> Cache dependencies to lower download time on build 

The message does communicate the intent, reducing build time.
It communicates how, though using caching.
However it does not clarify that it only affects continuous integration builds.
If the message were:

> ci: Cache dependencies to lower download time on build

It would effectively communicate the scope of the change.

**Comment by ChristianMurphy** [comment]
I've also added commitizen, a CLI tool that can help generate conventional commit messages.
Below is a demo of commitzen generating ad96e05

commitizen-demo

**Comment by apetro** [comment]
In-scope for backlogged [MUMMNG-3765](https://jira.doit.wisc.edu/jira/browse/MUMMNG-3765), which would track in MyUW Scrum allocating MyUW team attention to engaging with this. This isn't to say this can't naturally go to completion sooner; it is to say that it shouldn't be able to languish many more weeks before Scrum marshals engagement from MyUW team members.

**Comment by ChristianMurphy** [comment]
Resynced with `master` branch.

**Comment by apetro** [comment]
uPortal-home is now recognized on https://conventionalcommits.org/ .

**Pull request merged**
