### PR TITLE
Update welcome image to reflect changes

### PR DESCRIPTION
**Pull request by jhanstra**
image

### CODE REVIEW

**Comment by vertein** [comment]
Thoughts on changing the 'add to your homepage favorites' wording?  Maybe just 'add to home' or 'add to home page' to keep the top bubble consistent with the left bubble.

**Comment by timlevett** [comment]
Agreed with the removal of favs

**Comment by apetro** [comment]
Nitpick : "Switch between simple icons or informative widgets" 1) End with a period to be consistent with the other callouts.  2) I think "and" rather than "or" would sound more natural.

**Comment by apetro** [comment]
I agree with @vertein and @timlevett that striking "favorites" from the text is desirable.

**Comment by apetro** [comment]
Nuanced nitpick : The left hand bubble could be more about "Browse" and less about "find", that is, more like "Check out all the content in MyUW."  Whereas the tip bubble is already about "find".

**Comment by jhanstra** [comment]
Good catches, will change

**Comment by timlevett** [comment]
:cool: :+1:

**Comment by vertein** [comment]
1 spot it's 'home page' and another it's 'homepage'

**Comment by timlevett** [comment]
:+1: nice work @jhanstra . Merge?

**Pull request merged**
