### PR TITLE
MUMUP-2332 : Read only mode for search results

### PR DESCRIPTION
**Pull request by timlevett**
http://goo.gl/WcVtc8

Only change is the launch buttons

### CODE REVIEW

**Comment by jhanstra** [comment]
Nice, :+1:

**Comment by apetro** [comment]
:+1:

**Comment by keirserrie** [comment]
Not a dealbreaker but i'd prefer to stick with a link + icon like "add to home" - otherwise gonna have a ton of big red buttons on this page, no?

**Comment by timlevett** [comment]
@keirserrie not sure I follow. Talk f2f?

**Comment by keirserrie** [comment]
yep i'll stop by

**Comment by timlevett** [comment]
@keirserrie if you want to get a feel for it this is available now at https://public.predev.my.wisc.edu/web/apps. Thinking `btn-outline` would be nice here.

**Pull request merged**
