### PR TITLE
MUMUP-1628, MUMUP-1638: Mockups for Email, Calendar, My Courses

### PR DESCRIPTION
**Pull request by jhanstra**
This is how a real widget could look. Now all that's left is to swap out some real data :)

image

image

image

### CODE REVIEW

**Comment by timlevett** [comment]
:+1: , we may want to pull these demos out into a separate file just so they are not clouding the real content code. I know its temporary so more just random thought.

**Comment by apetro** [comment]
That's a fine idea you have there, @timlevett .  Much to be said for keeping `uw-master` continuously shippable. :smile: :shipit: .

**Comment by jhanstra** [comment]
Demos now pulled into separate directive and behind a beta flag

**Comment by timlevett** [comment]
:+1: Excellent way to demo the new designs and good footwork for future templating

**Pull request merged**
