### PR TITLE
Change all the things for ui-bootstrap upgrade

### PR DESCRIPTION
**Pull request by timlevett**
add uib- to a lotta stuff.

### CODE REVIEW

**Comment by Doug-Reed** [comment]
:+1:

**Comment by timlevett** [comment]
Depends on https://github.com/UW-Madison-DoIT/uw-frame/pull/171 to be merged, but that may wait

**Comment by Daha5** [comment]
:+1:

**Comment by vertein** [comment]
:+1: Looks good.

**Comment by apetro** [comment]
Conceptually :+1:, noting that either `master` needs to start marching towards `frame3` or this PR needs to track a different branch or just hang out for a while or something for this to fully make sense.

**Comment by timlevett** [comment]
Holding off on this for now

**Comment by timlevett** [comment]
Since we are moving to angular material anyway, closing this.

**Pull request closed without merging**
