### PR TITLE
Fix guest mode filter

### PR DESCRIPTION
**Pull request by timlevett**
+ Adds in flag check for "show all" if you are in guest mode
+ Changes out `btn-primary` to `btn-outline`
http://goo.gl/DeUiY3
+ Adds in mock `json` for guest layout and guest marketplace entries. 

If you want to use the mock objects for guest, you can just run this diff against your `app-config.js`
```diff
@@ -16,18 +16,18 @@ define(['angular'], function(angular) {
         })
         .constant('SERVICE_LOC', {
             'aboutURL' : '/portal/web/session.json',
-            'sessionInfo' : '/portal/web/session.json',
+            'sessionInfo' : '/portal/web/guest-session.json',
             'sidebarInfo' : '/web/staticFeeds/sidebar.json',
             'featuresInfo' : '/web/staticFeeds/features.json',
             'newstuffInfo': '/web/staticFeeds/new-stuff.json',
             'context'     : '/portal/',
             'base'        : '/portal/web/',
-            'layout'      : 'layoutDoc?tab=UW Bucky Home',
+            'layout'      : 'layoutDocGuest.json',
             'layoutTab' : 'UW Bucky Home',
             'marketplace' : {
                 'base' : 'marketplace/',
                 'entry' : 'entry/',
-                'entries' : 'entries.json'
+                'entries' : 'entries-guest.json'
             },

```

### CODE REVIEW

**Comment by apetro** [comment]
Worth capturing the how-to-configure-app-config-to-emulate-guest to a README somewhere?

**Comment by apetro** [comment]
:+1:

**Comment by timlevett** [comment]
@apetro good suggestion on the README.md, created one for the mock module.  Sure there can be more there eventually.

**Comment by jhanstra** [comment]
Really like the look of the outline buttons here :+1:

**Pull request merged**
