### PR TITLE
MUMUP-1912 : Add in back to classic link and config

### PR DESCRIPTION
**Pull request by timlevett**
+ Adds config for `feedback`
+ Adds config for `back to classic`
+ Adds config for `what's new`
+ Adds back to classic to the footer, if its configured

image
+ Hides if not configured or `null`

image

### CODE REVIEW

**Comment by jhanstra** [comment]
Thoughts on changing wording to 'Switch to Classic MyUW'? Other than that, :+1:. :D

**Comment by keirserrie** [comment]
I had it just as "MyUW Classic" but am flexible. https://docs.google.com/document/d/14X1v0N0TPWecEkVbLPwAw3YDZv0LMZ3SnQEwMwXrorg/edit

**Comment by keirserrie** [comment]
I want to make it so it's easy, but not obvious for someone who isn't looking for it. So you don't have somebody in the footer say "hey, i can switch back? sweet!" and we lose another user.

**Comment by jhanstra** [comment]
@keirserrie I like "MyUW Classic", agree with your logic

**Comment by timlevett** [comment]
neat, fixing

**Pull request merged**
