### PR TITLE
MUMMNG-1305: Change default smart widget call-to-action to sentence case

### PR DESCRIPTION
**Pull request by jhanstra**
image

### CODE REVIEW

**Comment by vertein** [comment]
:+1:

**Comment by apetro** [comment]
:+1: as far as it goes.  

@timlevett had been suggesting this might be an opportunity to refactor the call-to-action button to be a directive, maybe one that takes a parameter of the call-to-action text and defaults when that parameter not provided, so that we've abstracted out this control and can adjust it in one place affecting all its usages in the future.  Thoughts on whether that's worth doing at this juncture?  `#refactor_mercilessly`.

**Comment by keirserrie** [comment]
:+1:

**Comment by jhanstra** [comment]
@apetro @timlevett I'm not totally sold yet that there's a huge amount of value to be gained from making the button a directive - and the way our code is currently set up, it will require us to make some decisions about touch/click surfaces (because some of those buttons are `<button>`s and some are `<a>` links - in basic widgets the whole box is a link currently). So I think it's out of scope right now, but let's pick up a conversation about it when Tim gets back and see if it's worth doing.

**Comment by timlevett** [comment]
I agree @jhanstra . Might be challenging to create one.

**Pull request merged**
