### PR TITLE
MUMUP-1816: Removed serlet from WAR, updated parent pom for updated repositories.

### PR DESCRIPTION
**Pull request by tzodrow**
Updated WAR pom to remove unneeded dependencies - blocking development and not needed here
Updated Parent pom to update repository information

### CODE REVIEW

**Comment by nblair** [comment]
:+1:

**Comment by paulerickson** [comment]
:+1:

**Comment by timlevett** [comment]
@nblair @paulerickson @tzodrow  - this commit broke /frame, it is now undeployable. Was this tested?

**Comment by timlevett** [comment]
we are using jstl core in index.jsp

**Comment by nblair** [comment]
We tested with our application, but testing with MUM is not a known quantity to us. Is the dependency needed in -home and not -frame? What artifact are you deploying?

**Comment by nblair** [comment]
Let's get travis-ci enabled for this project, and come up with some builds that can help verify.

**Comment by timlevett** [comment]
We have frame setup as an independent app. Just /frame doesn't work.

**Comment by timlevett** [comment]
It builds fine, but when you hit index.jsp it throws an error because it can't find `http://java.sun.com/jsp/jstl/core`

**Comment by paulerickson** [comment]
I guess I've never hit index.jsp before, so I never saw the JSP compiler complain.  Is index.jsp doing anything?  It includes frame.html, but I don't see any jstl tags there.

**Comment by timlevett** [comment]
The `frame.html` has a versioned CSS file with the project version. Instead of changing that everytime we want to change the release we are using `${project.version}`. I'm all for alternative methods if you have a suggestion, this was just how we knew it would work. If that makes sense.

I'm surprised your styling isn't messed up if you didn't hit index.jsp. Are you just using frame.html? Or are you overwriting the index page all together?

**Comment by paulerickson** [comment]
Ohh, I see.  I did run into that intermittently, actually, but I blamed it on my local changes with requirejs.  I have to think my IDE is compiling the JSP despite the missing pom dependency or something.

**Pull request merged**
