### PR TITLE
MUMUP-1969 : Make it a pretty button, and forget favorites

### PR DESCRIPTION
**Pull request by timlevett**
#### Desktop:
http://goo.gl/4c8y9w

#### Mobile:
http://goo.gl/sbsuuG

#### Mobile w/ beta flag set to show toggle
http://goo.gl/c7Nn0X

### CODE REVIEW

**Comment by vertein** [comment]
:+1:

**Comment by jhanstra** [comment]
I might add a bit of padding around the button and see how that looks later but it's a :+1: from me

**Comment by apetro** [comment]
:+1:

**Comment by keirserrie** [comment]
agree on padding and :+1:

**Comment by timlevett** [comment]
The extra padding would break the toggle.

**Pull request merged**
