### PR TITLE
MUMUP-1976: Change welcome image

### PR DESCRIPTION
**Pull request by jhanstra**
Forgot to change the welcome image in the last pull request.

### CODE REVIEW

**Comment by timlevett** [comment]
Did you mean to make it twice as big? Are we putting a bootstrap scale thingy on this?

**Comment by vertein** [comment]
Being up to date is cool. :+1:

**Comment by vertein** [comment]
twice as big twice as fun

**Comment by jhanstra** [comment]
I think I just exported with a better screen resolution this time.

**Comment by apetro** [comment]
:+1:

**Comment by jhanstra** [comment]
Oh, and there is css to make it 100% of the available width, so that 2x bigger shouldn't screw anything up. But I will go make sure :)

**Comment by jhanstra** [comment]
Yep we're good with styling

**Pull request merged**
