### PR TITLE
Cleanup Unused code

### PR DESCRIPTION
**Pull request by timlevett**
+ Removes everything under `bucky` in favor of `buckyless`
+ Removes extra bootstrap less
+ Removes old config files we no longer use
+ Fixes the `master_app-config.js`
+ Removes test results because that is just weird

### CODE REVIEW

**Comment by jhanstra** [comment]
:+1: :+1: :+1: :+1: :+1:

**Comment by timlevett** [comment]
much thumb, wow. :dog2:

**Comment by vertein** [comment]
no kidding, much thumb

**Comment by vertein** [comment]
I was 80% of the way through, so I thought I might as well finish.  Here's another :+1:

**Pull request merged**
