### PR TITLE
MUMUP-1440 : Ga filter events

### PR DESCRIPTION
**Pull request by timlevett**
+ Adds in logging for ga events for localhosting
+ Adds in event for filters. Note it does wait until the filter is actually filtered (currently has a 250ms delay)

### CODE REVIEW

**Comment by vertein** [comment]
How does this handle going to the marketplace page, then typing something in.  Does this capture that initial filter event?

**Comment by timlevett** [comment]
@vertein - it captures every time the real time filter happens.

**Comment by timlevett** [comment]
@vertein - confirmed expected behavior

**Comment by vertein** [comment]
@timlevett cool beans. :+1:

**Pull request merged**
