### PR TITLE
Sample mumup 123

### PR DESCRIPTION
**Pull request by apetro**
Don't actually merge this, just an example.

### CODE REVIEW

**Comment by vertein** [comment]
:+1: - for example

**Comment by timlevett** [comment]
:-1: example says don't merge :D

**Comment by vertein** [comment]
:ghost: this scares me 2Spooky4me

**Comment by timlevett** [comment]
:wolf:

**Comment by apetro** [comment]
This branch got un-clean, what with conflating CONTRIBUTING documentation and getting started documentation. Abandoning and will try again in a clean branch.

**Pull request closed without merging**
