### PR TITLE
MUMUP-2149 : rename sample staticFeeds

### PR DESCRIPTION
**Pull request by jiayinjx**
Update_rename 'samples" to "staticFeeds"

### CODE REVIEW

**Comment by jhanstra** [comment]
:+1:

**Comment by timlevett** [comment]
What do we think of naming this folder `staticFeeds` instead? Since... they are not dynamic? Or just `static`. Just thought I had as I was reviewing this.

**Comment by jiayinjx** [comment]
update it just now.

**Comment by timlevett** [comment]
:+1:

**Pull request merged**
