### PR TITLE
MUMUP-2199 : Wisc edu search

### PR DESCRIPTION
**Pull request by timlevett**
+ Add in wisc.edu search results (looking at mock data right now
+ Revamp myuw search results to be more specific (variable renames)
+ Shows 1-10 of x with link to wisc.edu of that search. (Keir's suggestion)

Styling based on mockups : https://docs.google.com/presentation/d/18OzygRCY4npTOu_tnBgUogLitto0kjWMRRz1t7Cn8dQ/edit#slide=id.g74158e4a7_0_24

+ Overall
http://goo.gl/GOphOc
+ View more link
http://goo.gl/QTROVT

### CODE REVIEW

**Comment by keirserrie** [comment]
I made some nitpicky style suggestions to tim L....

**Comment by timlevett** [comment]
Love the detail @keirserrie . Will cleanup the frame of this page to be zazzier :tm: .

**Comment by vertein** [comment]
:+1:

**Comment by timlevett** [comment]
Updated Screenshot @keirserrie

**Comment by jhanstra** [comment]
Maybe more padding between the entries? Also for the 'View More' link, I'd suggest lower-casing More. Those are my only nitpicks, this looks awesome @timlevett!

**Comment by keirserrie** [comment]
Yes! Sorry, just notine? other nitpicks--if possible can you add 3px padding above tabs and remove 10px between headings (e.g. MyUW, Directory) and dividing line?

screenshot 2016-01-26 11 45 10

then :+1:

**Comment by timlevett** [comment]
Sure, fixing styles.

**Comment by timlevett** [comment]
+ Added 10px of padding between results (5px top, 5px bottom)
+ Added 3px of padding to the page top
+ Removed a 20px margin on hr (just changed to `margin: 0`)
+ Added `margin: 10px 0 1px;` to the subheaders (10px top, 0 lr, and 1px bottom)
+ Added 10px of padding on the left so text doesn't go right to the edge before wrapping
+ Fixed casing on more

Now looks like this:

http://goo.gl/ETjgvA

http://goo.gl/mmo6TL

**Comment by keirserrie** [comment]
:+1:

**Comment by jhanstra** [comment]
:+1:

**Pull request merged**
