### PR TITLE
Add a ridiculously bad build-every-minute script.

### PR DESCRIPTION
**Pull request by apetro**
Adds a ridiculously bad shell script to build every minute.

Intended as a starting point for collaborating on something that would, say, only build on changes.

The thing is, I'm already finding this ridiculous script helpful to my flow.

### CODE REVIEW

**Comment by timlevett** [comment]
have you ever heard of `crontab`?

**Comment by apetro** [comment]
Yup.  If this was all this script was ever going to be, well, then it would stay ridiculous.  Again, intended as a starting point for collaborating on something better.

**Comment by jhanstra** [comment]
So this will automatically run mvn tomcat7:redeploy in both frame and home every minute with any new changes made?

**Comment by apetro** [comment]
@jhanstra yes.  With any new changes made, and without any changes if there aren't any.

Which, as @timlevett points out, is almost exactly what you'd get if you scheduled the `build.sh` on a `crontab`.  (Subtly different in that this waits a minute between runs, whereas a naive `crontab` would be about scheduling build starts regardless of duration.)

**Comment by jhanstra** [comment]
:+1:

**Comment by vertein** [comment]
Appears at worse case, I won't run this.

**Pull request merged**
