### PR TITLE
[WIP] Use directive for home

### PR DESCRIPTION
**Pull request by timlevett**
+ Comment out current header
+ Use `portlet-header` directive, smaller size, with variable background, no toggle
http://goo.gl/qTJFvn

### CODE REVIEW

**Comment by keirserrie** [comment]
:+1: Nicely done, I still need to figure out what goes in that header

**Comment by timlevett** [comment]
@keirserrie thanks! I did it more as a conversation starter. What do we really want.  Also did this for fun: http://goo.gl/s4al4p

**Comment by keirserrie** [comment]
Good to have options...like the idea of no header on home, but may need to rethink the top part. Good stuff

**Comment by timlevett** [comment]
Chatted with Keir, lets merge this and see what happens.

**Comment by apetro** [comment]
:+1: It's an improvement.  Merging this makes it better now, and it can be made more better later.

**Pull request merged**
