### PR TITLE
MUMUP-1953   

### PR DESCRIPTION
**Pull request by jiayinjx**
Update a label to match updated branding of the CareerLocker external service.

### CODE REVIEW

**Comment by jhanstra** [comment]
:+1:

**Comment by timlevett** [comment]
Please note that this doesn't satisfy the issue, just the mock data. You will have to change uPortal entity files in order to do this issue.

**Comment by jiayinjx** [comment]
Not quite understand, could you explain a littler bit more?

in my test, it shows the label:CareerLocker instead of WISCareers, is that
what supposed to be?

**Comment by timlevett** [comment]
The file you are modifying is just for the mock data, not for the real data in production. This data really comes from entity files that are managed in SVN on site, which you probably don't have access to. That is okay, but you should also update https://github.com/UW-Madison-DoIT/uPortal/blob/uw-master/uportal-war/src/main/data/uw_quickstart_entities/portlet-definition/wiscareers.portlet-definition.xml as part of this.

**Comment by jiayinjx** [comment]
MUMUP-1971 manually update

**Comment by timlevett** [comment]
Please create one PR per pull request, MUMUP-1971 and MUMUP-1953 are not related.

**Comment by jiayinjx** [comment]
I was push then separately, don't know why they combined together.

**Pull request closed without merging**
