### PR TITLE
MUMUP-1615 : Create configuration for widgets

### PR DESCRIPTION
**Pull request by timlevett**
+ This will make `option-link` 100% reusable
+ Adds in a config object that is needed to configure where to get the JSON
```json
{
 "value" : "uri", 
 "display" : "email", 
 "arrayName" : "linked", 
 "singleElement" : true
}
```
+ Has defaults if someone doesn't want to supply config
+ Refactors to a controller instead of a link function for the directive

### CODE REVIEW

**Comment by timlevett** [comment]
Requires https://github.com/UW-Madison-DoIT/uPortal/pull/322

**Comment by jhanstra** [comment]
:+1:

**Comment by jhanstra** [comment]
Looks good. I like the comment outlining the config object. :+1:

**Comment by timlevett** [comment]
Thanks for the quick turn around @vertein @jhanstra

**Pull request merged**
